### ISSUE TITLE
(Internal Compiler Error) Sanity check failed for collapseProperties?

### ISSUE THREAD

**Issue by blickly** [google/closure-compiler#244]
This issue was imported from Closure Compiler's previous home at http://closure-compiler.googlecode.com

The original discussion is archived at:
http://blickly.github.io/closure-compiler-issues/#1012

**Comment by Dominator008** [comment]
The code is:
```js
// crash.js
var ss = {};
ss.isUndefined = function ss$isUndefined(o) {
	return (o === undefined);
};
```
Repro command:
```
java -jar build/compiler.jar  -O ADVANCED --jscomp_dev_mode=EVERY_PASS --js crash.js
```

**Comment by MatrixFrog** [comment]
Likely fixed by now.

https://closure-compiler-debugger.appspot.com/#input0%3Dvar%2520ss%2520%253D%2520%257B%257D%253B%250Ass.isUndefined%2520%253D%2520function%2520ss%2524isUndefined(o)%2520%257B%250A%2520%2520%2520%2520return%2520(o%2520%253D%253D%253D%2520undefined)%253B%250A%257D%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26COLLAPSE_PROPERTIES%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

**Comment by Dominator008** [comment]
@MatrixFrog I think you need `--jscomp_dev_mode=EVERY_PASS` to trigger yet. It was still crashing for me yesterday.
