### ISSUE TITLE
Essential code is removed from function body

### ISSUE THREAD

**Issue by dmitrysteblyuk** [google/closure-compiler#2555]
So basically this:

```js
const w = typeof window == 'object' ? window : {};
const _FormData = w['FormData'];
function isFormData(d) {
    return d instanceof _FormData;
}
window.isFormData = isFormData;

```
Compiles to this:
```js
window.a=function(){return!1};
```

Compiler options:
```
--compilation_level=ADVANCED_OPTIMIZATIONS
--language_in=ES6
--language_out=ES5

./test.js
--js_output_file=./dist/test.js
--entry_point=./test

```

**Comment by MatrixFrog** [comment]
This looks the same as this internal report: b/37975351 which says it was fixed by c3f5e9a5713cdd9af9283e75c309e5d831f1b45e

**Comment by dmitrysteblyuk** [comment]
@MatrixFrog I downloaded the most recent version (20170626). The internally reported issue ```const Foo = window['Foo'] || ...``` is fixed alright. Mine's still there.

**Comment by Dominator008** [comment]
@dmitrysteblyuk You mean your issue is still there. i.e. the code missing?

**Comment by dmitrysteblyuk** [comment]
@Dominator008 sorry for not being explicit. Yes, last time I checked (v20170626) the issue was not fixed.

**Comment by brad4d** [comment]
`--print_source_after_each_pass` shows that `smartNamePass` is removing it.

```
// earlyInlineVariables yields:
// ************************************
/** @const @constructor */ var _FormData = (typeof window == "object" ? window : {})["FormData"];
window.isFormData = function isFormData(d) {
  return d instanceof _FormData;
};

// ************************************

// smartNamePass yields:
// ************************************
window.isFormData = function isFormData(d) {
  return false;
};

// ************************************
```

**Comment by brad4d** [comment]
Imported and sent for internal review

**Comment by brad4d** [comment]
sorry, disregard that last. It was intended for pr #2554

**Comment by lauraharker** [comment]
This is fixed, probably by Bradford getting rid of SmartNamePass.

Original repro now compiles to
```
var b=("object"==typeof window?window:{}).FormData;window.a=function(c){return c instanceof b};
```
