### ISSUE TITLE
Incorrect DCE of assignment to destructered parameter field with ES_2015 or higher

### ISSUE THREAD

**Issue by WearyMonkey** [google/closure-compiler#3499]
Code sample: 

```
function installBaa({ obj }) {
    obj.baa = 'foo';
}

const obj = {};
installBaa({ obj });
console.log(obj.baa);
```

Command:

```
java -jar compiler.jar --js test.js -O ADVANCED --language_out ECMASCRIPT_2015
```

Version: `v20191027`

Expected output: (as output by `--language_out ECMASCRIPT5`)
```
console.log({a:"foo"}.a);
```

Actual output:
```
'use strict';console.log({}.a);
```

It looks like CC is losing the assignment when the target language is `ECMASCRIPT_2015` or higher. 

The following non-destructered parameter works as expected:

```
function installRoutes(x) {
    x.obj.baa = 'foo';
}
```

**Comment by lauraharker** [comment]
Created internal Google issue http://b/143889127

**Comment by lauraharker** [comment]
[Here's a smaller repro](https://closure-compiler-debugger.appspot.com/#input0%3Dconst%2520obj%2520%253D%2520%257B%257D%253B%250A%250A(function()%2520%257B%250A%2520%2520const%2520%257Bobj%253A%2520objLocal%257D%2520%253D%2520%257Bobj%257D%253B%250A%2520%2520objLocal.baa%2520%253D%2520%2522foo%2522%253B%250A%257D)()%253B%250A%250Aconsole.log(obj.baa)%253B%26input1%26conformanceConfig%26externs%3Dvar%2520console%253B%250Aconsole.log%253B%26refasterjs-template%26CHECK_TYPES%3Dtrue%26COMPUTE_FUNCTION_SIDE_EFFECTS%3Dtrue%26FOLD_CONSTANTS%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue):

``` js
const obj = {};

(function() {
  const {obj: objLocal} = {obj};
  objLocal.baa = "foo";
})();

console.log(obj.baa);
```

becomes with the FOLD_CONSTANTS and COMPUTE_FUNCTION_SIDE_EFFECTS flags:

``` js
const obj = {};
console.log(obj.baa);
```

For whatever reason the peephole passes think the IIFE is a no-op and are deleting it.

**Comment by WearyMonkey** [comment]
@lauraharker 

Any update on this issue?

It forces us to introduce Babel into our pipeline to transpile spread operators before passing Closure Compiler.

**Comment by lauraharker** [comment]
Hi, I'm afraid I don't have an update :( This is on our hotlist of issues to prioritize but no one is working on it at the moment.

I'll try to take a look this week.

**Comment by WearyMonkey** [comment]
Thank you!

**Comment by lauraharker** [comment]
Update: I have a fix and am in the process of internal code review. This should be fixed in the next release.

**Comment by WearyMonkey** [comment]
@lauraharker I just tested my sample code in `v20200719` and it's still not working?

Did you fix make it into the release?

**Comment by lauraharker** [comment]
Sorry about that, I'll reopen this issue.

[link to your original repro](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540language_out%2520ECMASCRIPT_2015%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Afunction%2520installBaa(%257B%2520obj%2520%257D)%2520%257B%250A%2520%2520%2520%2520obj.baa%2520%253D%2520'foo'%253B%250A%257D%250A%250Aconst%2520obj%2520%253D%2520%257B%257D%253B%250AinstallBaa(%257B%2520obj%2520%257D)%253B%250Aconsole.log(obj.baa)%253B)
