### ISSUE TITLE
Including jQuery + jQuery externs crashes compiler

### ISSUE THREAD

**Issue by blq** [google/closure-compiler#3594]
Can be shown by running this snippet in the compiler service:
```
// ==ClosureCompiler==
// @compilation_level SIMPLE_OPTIMIZATIONS
// @output_file_name default.js
// @externs_url https://raw.githubusercontent.com/google/closure-compiler/master/contrib/externs/jquery-3.3.js
// @warning_level VERBOSE
// @code_url https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js
// ==/ClosureCompiler==

// ADD YOUR CODE HERE
function hello(name) {
  alert('Hello, ' + name);
  
  // use anything from jQuery
  //jQuery(name).show(); 
  $(name).show();
}
hello('New user');
```

---
compiler output from my own compile:
```
java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

com.google.javascript.rhino.jstype.UnionType cannot be cast to com.google.javascript.rhino.jstype.ObjectType
  Node(SCRIPT): Q:/Distribution/javaScript/Closure/externs/jquery-3.3.js:33:0
var jQuerySelector;
  Parent(ROOT): [source unknown]

        at com.google.javascript.jscomp.FunctionTypeBuilder.inferInheritance(FunctionTypeBuilder.java:485)
        at com.google.javascript.jscomp.TypedScopeCreator$AbstractScopeBuilder.createFunctionTypeFromNodes(TypedScopeCreator.java:1759)
        at com.google.javascript.jscomp.TypedScopeCreator$AbstractScopeBuilder.defineFunctionLiteral(TypedScopeCreator.java:1343)
        at com.google.javascript.jscomp.TypedScopeCreator$NormalScopeBuilder.visitPreorder(TypedScopeCreator.java:2979)
        at com.google.javascript.jscomp.TypedScopeCreator$AbstractScopeBuilder.shouldTraverse(TypedScopeCreator.java:900)
        at com.google.javascript.jscomp.NodeTraversal.handleScript(NodeTraversal.java:803)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:839)
        at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:979)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:863)
        at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:979)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:863)
        at com.google.javascript.jscomp.NodeTraversal.traverseWithScope(NodeTraversal.java:444)
        at com.google.javascript.jscomp.NodeTraversal.traverseAtScope(NodeTraversal.java:545)
        at com.google.javascript.jscomp.TypedScopeCreator$AbstractScopeBuilder.build(TypedScopeCreator.java:846)
        at com.google.javascript.jscomp.TypedScopeCreator.createScopeInternal(TypedScopeCreator.java:449)
        at com.google.javascript.jscomp.TypedScopeCreator.createScope(TypedScopeCreator.java:387)
        at com.google.javascript.jscomp.PassConfig.regenerateGlobalTypedScope(PassConfig.java:55)
        at com.google.javascript.jscomp.DefaultPassConfig$GlobalTypeResolver.process(DefaultPassConfig.java:1892)
        at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:326)
        at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:235)
        at com.google.javascript.jscomp.Compiler.check(Compiler.java:1032)
        at com.google.javascript.jscomp.Compiler.performChecksAndTranspilation(Compiler.java:832)
        at com.google.javascript.jscomp.Compiler.lambda$stage1Passes$0(Compiler.java:762)
        at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:102)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassCastException: com.google.javascript.rhino.jstype.UnionType cannot be cast to com.google.javascript.rhino.jstype.ObjectType
        ... 28 more
```

**Comment by nreid260** [comment]
I don't actually understand what possible code-path could be causing this crash. There doesn't seem to be one.

That said, it seems like you're feeding both the jQuery externs and minification. That's not the intent of the compiler. Only the externs should be part of the compilation. In general the minification is shipped as is.

I can't reproduce this otherwise.

**Comment by blq** [comment]
Ok.. I've been doing that a long time :) I include jQuery, to get compression & bundling, by adding `goog.provide('jQuery')` to its header (minimal modification of a 3rd part lib). Then use the externs to get type-info for warnings. Is that not reasonable use? Worked kindof ok with the older versions of jQuery+extern, that's why I reported this when trying to upgrade.

**Comment by concavelenz** [comment]
This looks like an issue that was fixed back in January. 

https://github.com/google/closure-compiler/commit/c9b6530c2deb3d312d06a0e3497889d25464bffb#diff-d4041a613dd25518ee9d3bf772042016

Was there a problem with the webservice push?

Anyway, the webservice no longer crashing when I checked it today.

**Comment by blq** [comment]
@concavelenz No, my snippet above still crashes the online service. 
It seems to be enabling "@warning_level VERBOSE" that makes it go down! Maybe you ran it without that setting.
